import type { Metadata } from 'next';
import Gilroy from 'next/font/local';
import './globals.css';

const gilroy = Gilroy({
  src: [
    {
      path: './fonts/Gilroy-Medium.woff2',
      weight: '500',
    },
    {
      path: './fonts/Gilroy-Bold.woff2',
      weight: '700',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Read Journey',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${gilroy.className} antialiased`}>{children}</body>
    </html>
  );
}
